let allItems = [];
const grid = document.getElementById('grid');
const statusEl = document.getElementById('status');
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function badge(score){return score>=85?'🔥 Exceptional':score>=70?'🟢 Strong':score>=55?'🟡 Investigate':'🔴 Skip'}
function dateFmt(v){if(!v)return'See notice';const d=new Date(v);return Number.isNaN(d.valueOf())?'See notice':d.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}
function card(o){return `<article class="card"><div class="cardTop"><span class="source">${esc(o.source)}</span><span class="score">${esc(o.score)}/100</span></div><div class="verdict">${badge(o.score)}</div><h3>${esc(o.title)}</h3><div class="agency">${esc(o.agency)}</div><div class="meta"><span>📍 ${esc(o.location||'See notice')}</span><span>⏰ ${esc(dateFmt(o.deadline))}</span></div><p class="desc">${esc(o.description||'Open the solicitation for details.')}</p><div class="tags">${(o.tags||[]).map(t=>`<span>${esc(t)}</span>`).join('')}</div><div class="facts"><div><small>TYPE</small><b>${esc(o.type||'Opportunity')}</b></div><div><small>SET-ASIDE</small><b>${esc(o.setAside||'Not specified')}</b></div><div><small>VALUE</small><b>${esc(o.value||'Not disclosed')}</b></div></div><a class="open" href="${esc(o.url)}" target="_blank" rel="noreferrer">View original solicitation ↗</a></article>`}
function render(items){grid.innerHTML=items.length?items.map(card).join(''):'<div class="loading">No opportunities match this filter.</div>'}
async function load(){try{const r=await fetch('/api/opportunities');const data=await r.json();allItems=data.items||[];statusEl.textContent=data.mode==='live'?'● Live SAM.gov data':'● Demo data — add SAM_API_KEY';statusEl.classList.add(data.mode);render(allItems)}catch(e){statusEl.textContent='● Feed unavailable';grid.innerHTML='<div class="loading">Could not load the feed.</div>'}}
document.getElementById('filters').addEventListener('click',e=>{if(e.target.tagName!=='BUTTON')return;document.querySelectorAll('#filters button').forEach(b=>b.classList.remove('active'));e.target.classList.add('active');const f=e.target.dataset.filter;let items=allItems;if(f==='Strong')items=allItems.filter(x=>x.score>=70);else if(f!=='all')items=allItems.filter(x=>x.source===f);render(items)});load();
