let allItems = [];
const grid = document.getElementById('grid');
const statusEl = document.getElementById('status');
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function badge(score){return score>=85?'🔥 Exceptional':score>=70?'🟢 Strong':score>=55?'🟡 Investigate':'🔴 Skip'}
function dateFmt(v){if(!v)return'See notice';const d=new Date(v);return Number.isNaN(d.valueOf())?'See notice':d.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}
function bullets(items,kind){if(!items||!items.length)return'';return `<div class="analysis ${kind}">${items.map(x=>`<div>${kind==='good'?'✓':'!'} ${esc(x)}</div>`).join('')}</div>`}
function card(o){return `<article class="card"><div class="cardTop"><span class="source">${esc(o.source)}</span><span class="score">${esc(o.score)}/100</span></div><div class="verdict">${badge(o.score)}</div><h3>${esc(o.title)}</h3><div class="agency">${esc(o.agency)}</div><div class="meta"><span>📍 ${esc(o.location||'See notice')}</span><span>⏰ ${esc(dateFmt(o.deadline))}</span></div><p class="desc">${esc(o.description||'Open the solicitation for details.')}</p><div class="recommendation">${esc(o.recommendation||'Review original solicitation')}</div>${bullets(o.positives,'good')}${bullets(o.risks,'risk')}<div class="tags">${(o.tags||[]).map(t=>`<span>${esc(t)}</span>`).join('')}</div><div class="facts"><div><small>TYPE</small><b>${esc(o.type||'Opportunity')}</b></div><div><small>SET-ASIDE</small><b>${esc(o.setAside||'Not specified')}</b></div><div><small>VALUE</small><b>${esc(o.value||'Not disclosed')}</b></div></div><a class="open" href="${esc(o.url)}" target="_blank" rel="noreferrer">View original solicitation ↗</a></article>`}
function render(items){grid.innerHTML=items.length?items.map(card).join(''):'<div class="loading">No government opportunities are available from the live source right now. Check back after the next refresh.</div>'}
async function load(){try{const r=await fetch('/api/opportunities');const data=await r.json();allItems=data.items||[];statusEl.classList.remove('live','demo');if(data.mode==='live'){statusEl.textContent='● Live government data';statusEl.classList.add('live')}else if(data.mode==='stale'){statusEl.textContent='● Cached government data · refresh pending';statusEl.classList.add('live')}else if(data.mode==='rate_limited'){statusEl.textContent='● Government source temporarily rate-limited';statusEl.classList.add('demo')}else{statusEl.textContent='● Government feed temporarily unavailable';statusEl.classList.add('demo')}render(allItems)}catch(e){statusEl.textContent='● Government feed temporarily unavailable';statusEl.classList.add('demo');grid.innerHTML='<div class="loading">Could not load the government opportunity feed.</div>'}}
document.getElementById('filters').addEventListener('click',e=>{if(e.target.tagName!=='BUTTON')return;document.querySelectorAll('#filters button').forEach(b=>b.classList.remove('active'));e.target.classList.add('active');const f=e.target.dataset.filter;let items=allItems;if(f==='Strong')items=allItems.filter(x=>x.score>=70);else if(f!=='all')items=allItems.filter(x=>x.source===f);render(items)});load();
