const examples=[
  {score:92,type:'Opening',title:'New medical office opening',why:['New commercial location','Recurring facility needs likely','Opportunity to reach the business early'],needs:['Cleaning','Security','IT','Signage']},
  {score:88,type:'Expansion',title:'Local company expanding into larger space',why:['More square footage','Potential vendor changes','Move-in services may be needed'],needs:['Cleaning','Moving','Furniture','IT']},
  {score:84,type:'Permit',title:'Commercial renovation permit filed',why:['Work is planned before occupancy','Multiple service categories may be needed','Timing signal appears before opening'],needs:['Cleanup','Trades','Dumpster','Security']},
  {score:80,type:'Private RFP',title:'Organization seeking recurring facility vendor',why:['Direct purchasing signal','Recurring contract potential','Defined business need'],needs:['Cleaning','Landscaping','Maintenance']}
];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function render(offer,location){const grid=document.getElementById('businessGrid');document.getElementById('businessFeedTitle').textContent=`Opportunities for ${offer}`;document.getElementById('businessFeedSubtitle').textContent=`Prototype results for ${location}. These cards are examples, not live leads yet.`;grid.innerHTML=examples.map(x=>`<article class="card signalCard"><div class="cardTop"><span class="source">${esc(x.type)} signal</span><span class="score">${x.score}/100</span></div><div class="verdict">${x.score>=90?'🔥 High match':'🟢 Strong match'}</div><h3>${esc(x.title)}</h3><div class="meta"><span>📍 ${esc(location)}</span><span>🎯 Matched to ${esc(offer)}</span></div><div class="recommendation">Why BidScout would surface this</div><div class="analysis good">${x.why.map(v=>`<div>✓ ${esc(v)}</div>`).join('')}</div><div class="tags">${x.needs.map(v=>`<span>${esc(v)}</span>`).join('')}</div><div class="facts"><div><small>SIGNAL</small><b>${esc(x.type)}</b></div><div><small>STATUS</small><b>Example / not live</b></div></div></article>`).join('')}
document.getElementById('businessMatcher').addEventListener('submit',e=>{e.preventDefault();const offer=document.getElementById('offerInput').value.trim()||'your service';const location=document.getElementById('locationInput').value.trim()||'your area';render(offer,location)});render('commercial cleaning','Massachusetts');
